// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyzlR_ISR7bHNfuXGrzE-eLvbeCCQYHUc',
    appId: '1:776110625136:web:d9b20d748c3b20280fffb5',
    messagingSenderId: '776110625136',
    projectId: 'sign-in-method-f4d46',
    authDomain: 'sign-in-method-f4d46.firebaseapp.com',
    storageBucket: 'sign-in-method-f4d46.firebasestorage.app',
    measurementId: 'G-9YB2S6D467',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3PiVp2RuN8H7gWbTYo0tKPPpYovjrtYo',
    appId: '1:776110625136:android:c2f8f4ffd3c304ae0fffb5',
    messagingSenderId: '776110625136',
    projectId: 'sign-in-method-f4d46',
    storageBucket: 'sign-in-method-f4d46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNrYEH-5FGpfi91McLfNFFRc2Itilz-ms',
    appId: '1:776110625136:ios:c03c9c53635ba6a60fffb5',
    messagingSenderId: '776110625136',
    projectId: 'sign-in-method-f4d46',
    storageBucket: 'sign-in-method-f4d46.firebasestorage.app',
    iosClientId: '776110625136-km9kkp70e8p90bjpu4mgh0k43491216i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthSystemFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNrYEH-5FGpfi91McLfNFFRc2Itilz-ms',
    appId: '1:776110625136:ios:c03c9c53635ba6a60fffb5',
    messagingSenderId: '776110625136',
    projectId: 'sign-in-method-f4d46',
    storageBucket: 'sign-in-method-f4d46.firebasestorage.app',
    iosClientId: '776110625136-km9kkp70e8p90bjpu4mgh0k43491216i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthSystemFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyzlR_ISR7bHNfuXGrzE-eLvbeCCQYHUc',
    appId: '1:776110625136:web:eadfc4fcb9ca8e210fffb5',
    messagingSenderId: '776110625136',
    projectId: 'sign-in-method-f4d46',
    authDomain: 'sign-in-method-f4d46.firebaseapp.com',
    storageBucket: 'sign-in-method-f4d46.firebasestorage.app',
    measurementId: 'G-745WK4B0R4',
  );
}
